# from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
# FIXME: enable dist-mode
matrix:
    include:
        - name: "Linux-Py3"
          os: linux
          env:
            - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
            - PYVER=""
        - name: "OsX-Py3"
          os: osx
          osx_image: xcode12
          env:
            - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
            - MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
            - MACOSX_DEPLOYMENT_TARGET="10.14"
            - PYVER=""

install:
  - wget https://repo.continuum.io/miniconda/$MINICONDA -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda install conda-build=2 anaconda-client
  - conda update -q conda-build
  
  #- conda update -q conda
  #- conda install conda-build
  #- conda install -c conda-forge conda-forge::conda-build
  # Useful for debugging any issues with conda
  - conda info -a
  - gcc --version

script:
  - conda build -c intel -c conda-forge --numpy=1.17 $PYVER --output-folder ./ conda-recipe
