#===============================================================================
# Copyright 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

name: Check PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, converted_to_draft]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  checklist:
    name: Close all checkboxes before moving from draft
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get pull request details
      id: pr
      uses: actions/github-script@v7
      with:
        script: |
          const pr_desc = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          core.setOutput('body', pr_desc.data.body)
          core.setOutput('draft', pr_desc.data.draft)
          core.setOutput('author', pr_desc.data.user.login)
    - name: Check if all checkboxes are checked
      id: checkboxes
      env:
        DESCRIPTION: ${{ steps.pr.outputs.body }}
      run: |
        UNCHECKED=$(echo "$DESCRIPTION" | grep -c '\[ \]' || true)
        echo "unchecked=$UNCHECKED" >> $GITHUB_OUTPUT
    - name: Fail if not all checkboxes are checked and PR is not draft
      if: ${{ (steps.pr.outputs.draft == 'false') && (steps.checkboxes.outputs.unchecked != '0') && (steps.pr.outputs.author != 'renovate') }}
      run: |
        echo "Unchecked checkboxes: ${{ steps.checkboxes.outputs.unchecked }}"
        exit 1
