name: renovate-validation

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/renovate-validation.yml
      - .github/renovate.json
  push:
    branches:
      - master
    paths:
      - .github/workflows/renovate-validation.yml
      - .github/renovate.json

jobs:
  validate:
    name: Renovate validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
        with:
          config_file_path: .github/renovate.json
