name: sklearn1.0
on:
  workflow_dispatch:
jobs:
  sklearn:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - name: Get run ID of "build_oneDAL" workflow
        id: get-run-id
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="oneDAL nightly build"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow "${WF_NAME}" --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Download artifact from "Test" workflow
        uses: actions/download-artifact@v4
        with:
          name: __release_lnx # Match name used in test.yml upload artifact step
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}

      - name: Show downloaded files
        run: ls -la
